### ISSUE TITLE
Typing for record became too loose after addition of Partial

### ISSUE THREAD

**Issue by hsarokina-ita** [colinhacks/zod#992]
This issue is related to: https://github.com/colinhacks/zod/issues/751

After updating zod version from v3.12.0 to v3.13.3 we started to receive the following TS error: `error TS2322: Type 'Partial<Record<string, string>>' is not assignable to type 'Record<string, string>'.
  'string' index signatures are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
`

We are using zod `record` with string keys and values. I think that returning Partial for string records is a bug, because we are sure, that all keys that record has are checked by zod and contain non-`undefined` value, but TS says that they can contain `undefined` that forces us to do extra checks in the later code to convince TS that all values are strings.

I've created a repo with simple reproduction to illustrate such use case better:
https://github.com/hsarokina-ita/zod-partial-record
`safeParse` returned `success: false` for object with `undefined` values, this means that zod checked for it to be defined. But at the same time I can assign record with undefined value to typing returned by parser.

**Comment by amuttsch** [comment]
I have a similar issue with a string key, but my value is not a `string` but a `z.union` of some objects. I don't want my record value to be optional, this seems to be contradictionay to the "everything is required until `.optional()` is called".

**Comment by colinhacks** [comment]
This was changes to more accurately reflect the type Zod actually validates. Zod can't do exhaustiveness checking - for instance it doesn't/can't verify that all elements of the enum show up as keys:

```ts
z.record(z.enum(['a', 'b', 'c']), z.string());
// => Record<'a' | 'b' | 'c', string>
```

This is inaccurate - Zod merely validates each key against the key schema, but can't guarantee that all three keys exist in the object. So a more accurate type is `Partial<Record<'a' | 'b' | 'c', string>>`.

But your right that wrapping in `Partial` was too permissive. Just updated the typings: 

```ts
z.record(z.string, z.string);
// Record<string,string>;

z.record(z.enum(['a', 'b', 'c']), z.string());
// => Partial<Record<'a' | 'b' | 'c', string>>

```

Merged in 3.13.3.

**Comment by alexanderhorner** [comment]
This still seems to be happening when using custom string literal types.
```ts
export const UUIDSchema = z.string().uuid() as z.ZodType<UUID>;
````

When defining a record with UUIDSchema as key, it will be Partial.

**Comment by AlexErrant** [comment]
@alexanderhorner Looking at [the source code](https://github.com/colinhacks/zod/blob/f7ad26147ba291cb3fb257545972a8e00e767470/src/types.ts#L3696), you should put UUID in a [`Brand`](https://zod.dev/?id=brand) to prevent `Partial`.
