### ISSUE TITLE
"Type instantiation is excessively deep and possibly infinite." when using Zod versions 3.23.0 and 3.23.1 together.

### ISSUE THREAD

**Issue by kerrigan-nm** [colinhacks/zod#3435]
We have multiple projects using Zod, and are currently tripping over a compatibility issue between a project which is still on zod 3.23.0 and one which we're attempting to upgrade to 3.23.3.

Consuming the 3.23.0 schemas from 3.23.3 results in the following error, which I've also reproduced between 3.23.0 and 3.23.1.

```
error TS2589: Type instantiation is excessively deep and possibly infinite.
```

Full reproduction [here](https://github.com/kerrigan-nm/zod-type-instantiation-error-replication), with a summary in the readme.

**Comment by kerrigan-nm** [comment]
I see what you're saying, but as some light pushback:

1. I've never seen this degree of incompatibility between patch versions of the same project (outside of an actual bug).
2. This significantly hampers the ability to publish a library of prefab zod schemas which would be consumed and extended by multiple consumers (our use case).
3. `npm` is explicitly designed to be able to handle various versions of a single package as sub-dependencies of direct dependencies, so the total incompatibility comes as a surprise in this case.

> it's not clear what should be done about this.

That's totally fair — I don't have a solution either :)

If it's a "hard problem" to solve, so be it, but I'm sure it'll keep coming up, and it might be worth identifying the root cause and figuring out a medium-to-long-term solution.

**Comment by henriquealbert** [comment]
I am experiencing the same issue as well. We are dealing with a large schema that is causing a significant slowdown in the project, especially when importing the schema to our working file. We attempted to resolve the issue by downgrading to version 3.22.4, but it did not have any effect.

**Comment by Ayterx** [comment]
I had the same issue here after upgrading to 3.23.X. Downgrading worked for me.

**Comment by lukebelbina** [comment]
I had the same issue in a mono repo with 2 packages using 3.23.6 and one using 3.23.5. I got them all on the same version and issue was fixed.

**Comment by catz** [comment]
Had the same issue with two repos 3.23.6 & 3.23.5. Updated 5 to 6, and the errors are gone.

**Comment by darbymanning** [comment]
I have this issue with `3.23.7` and `3.23.8`. Having to remain on `3.23.6` for now.

**Comment by benqus** [comment]
> I have this issue with `3.23.7` and `3.23.8`. Having to remain on `3.23.6` for now.

This worked for me too, cheers! 🍻

**Comment by georgeportillo** [comment]
Having this issue with @builder.io's qwik-city package:
<img width="821" alt="Screenshot 2024-09-16 at 6 42 31 PM" src="https://github.com/user-attachments/assets/6bc3e98c-3b14-4609-86e3-5fbec5a7f80c">

**Comment by K-Mistele** [comment]
Downgrading from 3.24.x to 3.23.6 fixed this for me.
