### ISSUE TITLE
Type inference when combining objects seems wrong

### ISSUE THREAD

**Issue by anler** [colinhacks/zod#2864]
Hi, sorry to bother you with this, I've been successfully using the lib until I ran into this issue I'm not sure if it's a misuse from my side or a bug/limitation in Zod.

I have these reusable types defined:

```typescript
import { z } from "zod"

const SuccessResponse = <T>(schema: z.Schema<T>) => z.object({
  success: z.literal(true),
  data: schema
})
const ErrorResponse = z.object({
  success: z.literal(false),
  error: z.string()
})
const Response = <T>(schema: z.Schema<T>) => z.discriminatedUnion(
  "success",
  [
    SuccessResponse(schema),
    ErrorResponse
  ]
)

const Model = z.object({name: z.string()})

const response: unknown = {success: true, data: null}
```

And I'm able to use them just fine in this case:
```typescript
const model = Response(Model).parse(response)
if (model.success) {
  model.data.name
} else {
  model.error
}
```

But if I try to abstract the above code in a function then the type of the `parse` result does not allow me to type-guard on the `success` field:
```typescript
function responseData<T>(schema: z.Schema<T>, response: unknown): T {
  const model = Response(schema).parse(response)
  if (model.success) {
    return model.data // 'data' does not exist on type
  }
  throw new Error(model.message) // 'message' does not exist on type
}
```

I have a codesandbox created with this code: https://codesandbox.io/p/sandbox/silly-wing-m4gnt8

**Comment by eastlondoner** [comment]
I am seeing the same issue with types that are working fine on zod `3.20.6` when upgrading to zod `3.22.4`
