### ISSUE TITLE
v4 optional function

### ISSUE THREAD

**Issue by peterpeterparker** [colinhacks/zod#4757]
Hi,

In zod `v3`, the following simple schema for a function — later used as the description of an object parameter — could be marked as optional:

```
const OnDisconnectSchema = z.function().args().returns(z.void()).optional();
```

After migrating to v4 using the guide, I'm no longer able to mark it as optional. Is this expected?

```
// TS2339: Property optional does not exist on type $ZodFunction<$ZodFunctionArgs, ZodVoid>
const OnDisconnectSchema = z.function({output: z.void()}).optional();
```

**Comment by peterpeterparker** [comment]
```
const OnDisconnectSchema = z.function({ output: z.void() });
const MyObject = z.object({
  onDisconnect: OnDisconnectSchema.optional()
});
```

does not work either: `TS2339: Property optional does not exist on type $ZodFunction<$ZodFunctionArgs, ZodVoid>`

```
const OptionalFn = z.union([OnDisconnectSchema, z.undefined()]);
```

Changes the behavior, the parameter is not optional but, becomes mandatory.

i.e. those two are not valid solutions.

**Comment by peterpeterparker** [comment]
The function cannot be made optional because in v4 those aren't schema anymore as mentionned in the migration guide, took me some time to understand what was written even though it's pretty clear.

> The result of z.function() is no longer a Zod schema. 

This is why `.optional()` cannot be used. So as mentionned in the doc, the solution was to use the [workaround](https://github.com/colinhacks/zod/issues/4143#issuecomment-2845134912) to stick to schema.
