### ISSUE TITLE
v3.25.64: TS2339 error when compiling the README code example

### ISSUE THREAD

**Issue by dejor** [colinhacks/zod#4696]
Hello,

I want to integrate Zod into a project and decided to play around with the code examples to get familiar with the library.

### Issue
Version: **v3.25.64**
When compiling the minimal code example from the [README](https://github.com/colinhacks/zod?tab=readme-ov-file#what-is-zod) I get the following TypeScript error.

```
node_modules/zod/dist/types/v4/core/util.d.ts:130:54 - error TS2339: Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.

130 export declare const captureStackTrace: typeof Error.captureStackTrace;
                                                         ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/zod/dist/types/v4/core/util.d.ts:130
```

#### Code

```ts
import { z } from "zod/v4";

const User = z.object({
  name: z.string(),
});

// some untrusted data...
const input = { name: "foo" /* stuff */ };

// the parsed result is validated and type safe!
const data = User.parse(input);

// so you can use it with confidence :)
console.log(data.name);
```

#### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "nodenext",
    "outDir": "dist",
    "strict": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*"]
}
```
#### Note
The example works with version **v3.25.63**.

**Comment by dejor** [comment]
Thank you! Adding `@types/node` as a dev dependency resolved the issue.

After reading "Zero external dependencies" in the README, I assumed it would work without dev dependencies.

I am new to TypeScript, so please excuse me if this is a dumb assumption.
