### ISSUE TITLE
Error after migration to V4 with Vinxi

### ISSUE THREAD

**Issue by mbauchet** [colinhacks/zod#4457]
After updating Zod to V4, got this error, using Tanstack Start:
`Error when evaluating SSR module $vinxi/handler/ssr: Cannot find module 'node_modules/zod/dist/v4/locales/en.js.js'`

Any idea?

**Comment by colinhacks** [comment]
Can you try this on the latest version? There was an issue with a specific version (3.25.15) but it's fixed in latest.
