### ISSUE TITLE
zod doesn't work with typescript `4.3.2`

### ISSUE THREAD

**Issue by KATT** [colinhacks/zod#473]
see #472

**Comment by prueker** [comment]
Ran into the same issue today when updating packages.

Keeping typescript at 4.2.4 works for now as a workaround.

**Comment by toresbe** [comment]
Thank you for filing this issue and giving a workaround. Can confirm that pinning TS to 4.2.3 solved our problem. 

For anyone Googling, this is the error we got:

`Excessive stack depth comparing types 'ZodError<?>' and 'ZodError<?>`

**Comment by KATT** [comment]
workaround in my monorepo: https://github.com/trpc/trpc/commit/ff184a91bdd3710d347338f0e74824ec8ae1fb32

**Comment by glitch452** [comment]
I also experienced the same issue.  Reverting to TS v4.2.4 solved it for now.  
Here are the errors I see.  Hope it helps!
```
error TS2321: Excessive stack depth comparing types 'ZodOptional<?>' and 'ZodOptional<?>'.
error TS2321: Excessive stack depth comparing types 'ZodError<?>' and 'ZodError<?>'.

z.union([z.string(), z.number(), z.boolean(), z.null()]);
error TS2321: Excessive stack depth comparing types 'ZodFormattedError<?>' and 'ZodFormattedError<?>'.

z.union([z.string(), z.number(), z.boolean(), z.null()]);
error TS2321: Excessive stack depth comparing types 'ZodIntersection<?, U>' and 'ZodIntersection<?, U>'.

z.union([z.string(), z.number(), z.boolean(), z.null()]);

error TS2321: Excessive stack depth comparing types 'ZodIntersection<T, ?>' and 'ZodIntersection<T, ?>'.
z.union([z.string(), z.number(), z.boolean(), z.null()]);

src/services/schemas.ts:10:30 - error TS2321: Excessive stack depth comparing types 'ZodNonEmptyArray<?>' and 'ZodNonEmptyArray<?>'.
z.union([z.string(), z.number(), z.boolean(), z.null()]);

error TS2321: Excessive stack depth comparing types 'ZodRecord<?>' and 'ZodRecord<?>'.
z.record(z.string().or(z.number())).optional(),
```
Ps. Love the library, keep up the awesome work!

**Comment by dmitryshostak** [comment]
Is anyone working on solving this issue?

**Comment by adam-thomas-privitar** [comment]
Hi guys. This has been raised on https://github.com/microsoft/TypeScript/issues/44299

**Comment by colinhacks** [comment]
Fixed in zod@3.2 - upgrade and it will work with TypeScript 4.3.2. 

This was a doozy. TS 4.3 added limitations on the self-referential recursive conditional types inside class methods, something that Zod relies on heavily. 

I managed to get everything working again with minimal disruption to the Zod's internals, but there's one minor change that was unavoidable. Certain methods (`.or` and `.transform`) now return a new instance that wrap the current instance. Previously Zod would try to avoid additional/unnecessary nesting. For example:

```ts
z.union([z.string(), z.number()]).or(z.boolean());
// previously
// => ZodUnion<[ZodString, ZodNumber, ZodBoolean]>

// now
// => ZodUnion<[ZodUnion<[ZodString, ZodNumber]>, ZodBoolean]>
```

With TypeScript 4.3.2 it was no longer possible to reflect the old type signature. In practice I think this change is minor and could almost be considered an internal change so I'm not bumping the major version. This behavior is actually more consistent and avoids certain pitfalls when implementing generic functions that operate on ZodSchemas, so it's not all bad.
