### ISSUE TITLE
v4: Regression in 3.25.73 - ZodReadonly around ZodRecord breaks within recursive unions...

### ISSUE THREAD

**Issue by webcarrot** [colinhacks/zod#4825]
Something like this has stopped working in `3.25.73` and it was working in `3.25.72`:

```ts
import * as z from 'zod/v4';

export type SomeRecursiveUnion1 = z.ZodUnion<
	[
		z.ZodObject<{
			foo: z.ZodReadonly<z.ZodRecord<z.ZodString, SomeRecursiveUnion1>>;
		}>,
	]
>;

// But it works without `z.ZodReadonly` or without recursive reference:

export type SomeRecursiveUnion2 = z.ZodUnion<
	[
		z.ZodObject<{
			foo: z.ZodRecord<z.ZodString, SomeRecursiveUnion2>;
			bar: z.ZodReadonly<z.ZodRecord<z.ZodString, z.ZodString>>;
		}>,
	]
>;
```

TSC Error:

```
error TS2344: Type '{ foo: ZodReadonly<ZodRecord<ZodString, SomeRecursiveUnion1>>; }' does not satisfy the constraint 'Readonly<{ [k: string]: $ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>; }>'.
  Property 'foo' is incompatible with index signature.
    Type 'ZodReadonly<ZodRecord<ZodString, SomeRecursiveUnion1>>' is not assignable to type '$ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>'.
      The types of '_zod.optin' are incompatible between these types.
        Type 'unknown' is not assignable to type '"optional" | undefined'.

5   z.ZodObject<{
                ~
6    foo: z.ZodReadonly<z.ZodRecord<z.ZodString, SomeRecursiveUnion1>>;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7   }>,
```

**Comment by colinhacks** [comment]
Fixed in latest, thanks!
