### ISSUE TITLE
Getting "Type import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute."

### ISSUE THREAD

**Issue by Maxim-Mazurok** [colinhacks/zod#5560]
When updating from 4.1.13 to 4.2.1, I'm getting this error:

```text
> google-api-typings-generator@0.1.0 type-check
> tsc --noEmit

node_modules/zod/v4/core/json-schema-generator.d.cts:34:36 - error TS1542: Type import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.

34     get metadataRegistry(): import("./registries.js").$ZodRegistry<Record<string, any>, schemas.$ZodType<unknown, unknown, schemas.$ZodTypeInternals<unknown, unknown>>>;
                                      ~~~~~~~~~~~~~~~~~

node_modules/zod/v4/core/json-schema-generator.d.cts:51:109 - error TS1542: Type import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.

51     get seen(): Map<schemas.$ZodType<unknown, unknown, schemas.$ZodTypeInternals<unknown, unknown>>, import("./to-json-schema.js").Seen>;
                                                                                                               ~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/zod/v4/core/json-schema-generator.d.cts:34
```

For more context see update PR: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/1206

This patch seems to resolve the issue:

```patch
diff --git a/node_modules/zod/v4/core/json-schema-generator.d.cts b/node_modules/zod/v4/core/json-schema-generator.d.cts
index 40258e5..f664989 100644
--- a/node_modules/zod/v4/core/json-schema-generator.d.cts
+++ b/node_modules/zod/v4/core/json-schema-generator.d.cts
@@ -31,7 +31,7 @@ type JSONSchemaGeneratorConstructorParams = Pick<JSONSchemaGeneratorParams, "met
 export declare class JSONSchemaGenerator {
     private ctx;
     /** @deprecated Access via ctx instead */
-    get metadataRegistry(): import("./registries.js").$ZodRegistry<Record<string, any>, schemas.$ZodType<unknown, unknown, schemas.$ZodTypeInternals<unknown, unknown>>>;
+    get metadataRegistry(): import("./registries.js", { with: { "resolution-mode": "import" } }).$ZodRegistry<Record<string, any>, schemas.$ZodType<unknown, unknown, schemas.$ZodTypeInternals<unknown, unknown>>>;
     /** @deprecated Access via ctx instead */
     get target(): ({} & string) | "draft-2020-12" | "draft-07" | "openapi-3.0" | "draft-04";
     /** @deprecated Access via ctx instead */
@@ -48,7 +48,7 @@ export declare class JSONSchemaGenerator {
     get counter(): number;
     set counter(value: number);
     /** @deprecated Access via ctx instead */
-    get seen(): Map<schemas.$ZodType<unknown, unknown, schemas.$ZodTypeInternals<unknown, unknown>>, import("./to-json-schema.js").Seen>;
+    get seen(): Map<schemas.$ZodType<unknown, unknown, schemas.$ZodTypeInternals<unknown, unknown>>, import("./to-json-schema.js", { with: { "resolution-mode": "import" } }).Seen>;
     constructor(params?: JSONSchemaGeneratorConstructorParams);
     /**
      * Process a schema to prepare it for JSON Schema generation.
```

**Comment by colinhacks** [comment]
Looking into it. Seems to be a type portability issue.
