### ISSUE TITLE
error: Cannot find module './zh-CN.js' from 'node_modules/.pnpm/zod@4.1.5/node_modules/zod/v4/locales/index.js' in bun

### ISSUE THREAD

**Issue by capaj** [colinhacks/zod#5219]
I have a project where I run bun test.
zod@4.1.4 works fine, but after upgrading to 4.1.5 I get:

```
bun test v1.2.21 (7c45ed97)

OrderBookStreamListenerBitget.test.ts:

# Unhandled error between tests
-------------------------------
error: Cannot find module './zh-CN.js' from '/home/capaj/work-repos/bun-crypto-bot/node_modules/.pnpm/zod@4.1.5/node_modules/zod/v4/locales/index.js'
-------------------------------


 0 pass
 1 fail
 1 error
Ran 1 test across 1 file. [1.93s]
```

seems like maybe there might be a file missing in the published artifact on NPM?

**Comment by colinhacks** [comment]
I can't find any reason why this would be happening. That file definitely exists. Sounds like a problem w/ bun install or module resolution. Feel free to create a new issue (with a minimal repro) if you confirm this is an issue with Zod. 👍

Working file:
```ts
// bun index.ts

import * as z from "zod";

import { zhCN } from "zod/locales";

z.config(zhCN())

z.string().parse(123);
```
