### ISSUE TITLE
Type errors in 3.25.3: Cannot find name 'T_1'

### ISSUE THREAD

**Issue by Rugvip** [colinhacks/zod#4417]
Hello! Quick report that I think something might be up with the latest 3.25.3 release. There's code like this in `/zod/dist/commonjs/v3/types.d.ts`:

```ts
static create: <T extends Readonly<[ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]>>(types: T_1, params?: RawCreateParams) => ZodUnion<T_1>;
```

Which of course leads to errors like this:

```plain
node_modules/zod/dist/commonjs/v3/types.d.ts:600:134 - error TS2304: Cannot find name 'T_1'.

     static create: <T extends Readonly<[ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]>>(types: T_1, params?: RawCreateParams) => ZodUnion<T_1>;
```

**Comment by colinhacks** [comment]
Investigating. It's a bug in TypeScript but I see a workaround.

**Comment by colinhacks** [comment]
Fix landed in `zod@3.25.4`

**Comment by Rugvip** [comment]
Confirmed it works with 3.25.4, thank you! 👍
