### ISSUE TITLE
Compilation error after updating from 3.20.6 to 3.21.0

### ISSUE THREAD

**Issue by norgepaul** [colinhacks/zod#2583]
After updating Zod from 3.20.6 to 3.21.0 I receive this error when compiling.

```
TS2345: Argument of type 'ZodObject<{ data: ZodObject<{ type: ZodLiteral<IotStateUpdateType.LOCK_STATE>; result: ZodNativeEnum<typeof IotLockEventResult>; }, "strip", ZodTypeAny, { ...; }, { ...; }>; ... 9 more ...; version: ZodOptional<...>; }, "strip", ZodTypeAny, { ...; }, { ...; }>' is not assignable to parameter of type 'ZodTypeAny'.
  Types of property '_parse' are incompatible.
    Type '(input: ParseInput) => ParseReturnType<{ expires?: Date | undefined; version?: number | undefined; sent?: Date | undefined; id: string; idType: IotIdType; data: { ...; }; ... 4 more ...; source: IotHardware; }>' is not assignable to type '(input: ParseInput) => ParseReturnType<any>'.
      Types of parameters 'input' and 'input' are incompatible.
        Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/helpers/parseUtil").ParseInput' is not assignable to type 'Zod.ParseInput'.
          The types of 'parent.common.issues' are incompatible between these types.
            Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodIssue[]' is not assignable to type 'Zod.ZodIssue[]'.
              Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodIssue' is not assignable to type 'Zod.ZodIssue'.
                Type 'ZodInvalidUnionIssue & { fatal?: boolean | undefined; message: string; }' is not assignable to type 'ZodIssue'.
                  Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodInvalidUnionIssue & { fatal?: boolean | undefined; message: string; }' is not assignable to type 'Zod.ZodInvalidUnionIssue & { fatal?: boolean | undefined; message: string; }'.
                    Type 'ZodInvalidUnionIssue & { fatal?: boolean | undefined; message: string; }' is not assignable to type 'ZodInvalidUnionIssue'.
                      Types of property 'unionErrors' are incompatible.
                        Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodError<any>[]' is not assignable to type 'Zod.ZodError<any>[]'.
                          Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodError<any>' is not assignable to type 'Zod.ZodError<any>'.
                            Types of property 'issues' are incompatible.
                              Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodIssue[]' is not assignable to type 'Zod.ZodIssue[]'.
                                Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodIssue' is not assignable to type 'Zod.ZodIssue'.
                                  Type 'ZodInvalidArgumentsIssue & { fatal?: boolean | undefined; message: string; }' is not assignable to type 'ZodIssue'.
                                    Type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodInvalidArgumentsIssue & { fatal?: boolean | undefined; message: string; }' is not assignable to type 'Zod.ZodInvalidArgumentsIssue & { fatal?: boolean | undefined; message: string; }'.
                                      Type 'ZodInvalidArgumentsIssue & { fatal?: boolean | undefined; message: string; }' is not assignable to type 'ZodInvalidArgumentsIssue'.
                                        The types of 'argumentsError.addIssue' are incompatible between these types.
                                          Type '(sub: import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodIssue) => void' is not assignable to type '(sub: Zod.ZodIssue) => void'.
                                            Types of parameters 'sub' and 'sub' are incompatible.
                                              Type 'Zod.ZodIssue' is not assignable to type 'import("/Users/paulthornton/Documents/GitHub/iot-bridge/node_modules/zod/lib/ZodError").ZodIssue'.
                                                Type 'ZodInvalidUnionIssue & { fatal?: boolean | undefined; message: string; }' is not assignable to type 'ZodIssue'.
    386 |       if (lockEventResult) {
    387 |         this.pubsubService.publishState(
  > 388 |           AxaSchema.StateMessage,
        |           ^^^^^^^^^^^^^^^^^^^^^^
    389 |           AxaDto.newStateMessage(
    390 |             payload.imei,
    391 |             {
```

I can provide more details if the cause isn't immediately obvious.

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.

**Comment by lcsvcn** [comment]
same error here
