### ISSUE TITLE
Applications fail to build with tsc 4.3.5 and zod 3.17.2 due to invalid import in parseUtil.d.ts

### ISSUE THREAD

**Issue by dolfandringa** [colinhacks/zod#1163]
When I try to compile my typescript application with tsc to js, and depend on zod 3.17.2, I get a number of compile errors:

```
 tsc -p tsconfig.json
node_modules/zod/lib/helpers/parseUtil.d.ts:1:15 - error TS1005: ',' expected.
1 import { type IssueData, type ZodErrorMap, type ZodIssue } from "../ZodError";
                ~~~~~~~~~

node_modules/zod/lib/helpers/parseUtil.d.ts:1:31 - error TS1005: ',' expected.
1 import { type IssueData, type ZodErrorMap, type ZodIssue } from "../ZodError";
                                ~~~~~~~~~~~

node_modules/zod/lib/helpers/parseUtil.d.ts:1:49 - error TS1005: ',' expected.
1 import { type IssueData, type ZodErrorMap, type ZodIssue } from "../ZodError";
                                                  ~~~~~~~~

node_modules/zod/lib/helpers/parseUtil.d.ts:2:15 - error TS1005: ',' expected.
2 import { type ZodParsedType } from "./util";
                ~~~~~~~~~~~~~
```
This is with the following compiler options:
```
  "compilerOptions": {
    "incremental": true, 
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "allowJs": true,
    "pretty": true,
    "declaration": true,
    "sourceMap": true,
    "removeComments": true,
    "strict": true,
...
}

and 
```
tsc -V
Version 4.3.5
```.

Logging at the offending lines from `parseUtil.d.ts`:
```
import { type IssueData, type ZodErrorMap, type ZodIssue } from "../ZodError";
import { type ZodParsedType } from "./util";
```

I think those import statements should be:
```
import type { IssueData, ZodErrorMap, ZodIssue } from "../ZodError";
import type { ZodParsedType } from "./util";
```
Am I right? I would be happy to create a PR with the fix.

**Comment by dolfandringa** [comment]
Lol, just realized you released 3.17.3 which fixes it already. So nevermind. Sorry for the noise
