### ISSUE TITLE
Latest Zod3 now includes Zod4, which causes breaking changes on minor zod upgrade

### ISSUE THREAD

**Issue by souterjk** [colinhacks/zod#4923]
My team is using zod3, which is/was working fine with typescript 4.9. Recently a bump to a more recent version, zod 3.25.76, broke all builds and tests without any other changes. Digging around, there are tons of errors logs coming from zod4, which is odd because I'm still using zod3 according to my package.json and yarn.lock files. 

An example:
```
../node_modules/zod/v4/core/function.d.cts:26:11 - error TS1139: Type parameter declaration expected.

26     input<const Items extends util.TupleItems, const Rest extends $ZodFunctionOut = $ZodFunctionOut>(args: Items, rest?: Rest): $ZodFunction<schemas.$ZodTuple<Items, Rest>, Returns>;
             ~~~~~
```

After some investigation, it appears that someone added [zod4 as a library inside of zod3 recently.](https://www.npmjs.com/package/zod/v/3.25.76?activeTab=code) This means, that without a major version upgrade, you can be forced into having to upgrade from ts4 to ts5 just to stay on zod3. Zod3 is also now twice the size that it should be, because zod is basically included twice (as v3 and v4). 

Last working version: 3.22.4
Breaking version: 3.25.76

**Comment by colinhacks** [comment]
Apologies for the inconvenience here. Everything after 3.25.0 contains Zod 4. See the issues Dosu linked for more info. There are no significant changes to Zod 3 that have landed in the the 3.25.x version range, so I recommend pinning to `~3.24.0` if you wish to stick on TS4.9. (Though I'd strongly recommend upgrading TS if feasible.) As you have noted, Zod 4+ now requires TS5.5 and there are now two versions simultaneously published to npm at different subpaths.
